//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffBooking.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://localhost:63341/WebService.asmx", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:63341/WebService.asmx", ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name staffId from namespace http://localhost:63341/WebService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/LoginStaff", ReplyAction="*")]
        StaffBooking.ServiceReference.LoginStaffResponse LoginStaff(StaffBooking.ServiceReference.LoginStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/LoginStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffBooking.ServiceReference.LoginStaffResponse> LoginStaffAsync(StaffBooking.ServiceReference.LoginStaffRequest request);
        
        // CODEGEN: Generating message contract since element name staffID from namespace http://localhost:63341/WebService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/UserDetails", ReplyAction="*")]
        StaffBooking.ServiceReference.UserDetailsResponse UserDetails(StaffBooking.ServiceReference.UserDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/UserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffBooking.ServiceReference.UserDetailsResponse> UserDetailsAsync(StaffBooking.ServiceReference.UserDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name staffID from namespace http://localhost:63341/WebService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/MakeRequest", ReplyAction="*")]
        StaffBooking.ServiceReference.MakeRequestResponse MakeRequest(StaffBooking.ServiceReference.MakeRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/MakeRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffBooking.ServiceReference.MakeRequestResponse> MakeRequestAsync(StaffBooking.ServiceReference.MakeRequestRequest request);
        
        // CODEGEN: Generating message contract since element name staffID from namespace http://localhost:63341/WebService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/ViewAllRequests", ReplyAction="*")]
        StaffBooking.ServiceReference.ViewAllRequestsResponse ViewAllRequests(StaffBooking.ServiceReference.ViewAllRequestsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/ViewAllRequests", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffBooking.ServiceReference.ViewAllRequestsResponse> ViewAllRequestsAsync(StaffBooking.ServiceReference.ViewAllRequestsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginStaff", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public StaffBooking.ServiceReference.LoginStaffRequestBody Body;
        
        public LoginStaffRequest() {
        }
        
        public LoginStaffRequest(StaffBooking.ServiceReference.LoginStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class LoginStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginStaffRequestBody() {
        }
        
        public LoginStaffRequestBody(string staffId, string password) {
            this.staffId = staffId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginStaffResponse", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public StaffBooking.ServiceReference.LoginStaffResponseBody Body;
        
        public LoginStaffResponse() {
        }
        
        public LoginStaffResponse(StaffBooking.ServiceReference.LoginStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class LoginStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginStaffResult;
        
        public LoginStaffResponseBody() {
        }
        
        public LoginStaffResponseBody(bool LoginStaffResult) {
            this.LoginStaffResult = LoginStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserDetails", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public StaffBooking.ServiceReference.UserDetailsRequestBody Body;
        
        public UserDetailsRequest() {
        }
        
        public UserDetailsRequest(StaffBooking.ServiceReference.UserDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class UserDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffID;
        
        public UserDetailsRequestBody() {
        }
        
        public UserDetailsRequestBody(string staffID) {
            this.staffID = staffID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserDetailsResponse", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public StaffBooking.ServiceReference.UserDetailsResponseBody Body;
        
        public UserDetailsResponse() {
        }
        
        public UserDetailsResponse(StaffBooking.ServiceReference.UserDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class UserDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StaffBooking.ServiceReference.ArrayOfString UserDetailsResult;
        
        public UserDetailsResponseBody() {
        }
        
        public UserDetailsResponseBody(StaffBooking.ServiceReference.ArrayOfString UserDetailsResult) {
            this.UserDetailsResult = UserDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeRequest", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public StaffBooking.ServiceReference.MakeRequestRequestBody Body;
        
        public MakeRequestRequest() {
        }
        
        public MakeRequestRequest(StaffBooking.ServiceReference.MakeRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class MakeRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime start;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime end;
        
        public MakeRequestRequestBody() {
        }
        
        public MakeRequestRequestBody(string staffID, System.DateTime start, System.DateTime end) {
            this.staffID = staffID;
            this.start = start;
            this.end = end;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeRequestResponse", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public StaffBooking.ServiceReference.MakeRequestResponseBody Body;
        
        public MakeRequestResponse() {
        }
        
        public MakeRequestResponse(StaffBooking.ServiceReference.MakeRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MakeRequestResponseBody {
        
        public MakeRequestResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewAllRequestsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewAllRequests", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public StaffBooking.ServiceReference.ViewAllRequestsRequestBody Body;
        
        public ViewAllRequestsRequest() {
        }
        
        public ViewAllRequestsRequest(StaffBooking.ServiceReference.ViewAllRequestsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class ViewAllRequestsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffID;
        
        public ViewAllRequestsRequestBody() {
        }
        
        public ViewAllRequestsRequestBody(string staffID) {
            this.staffID = staffID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewAllRequestsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewAllRequestsResponse", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public StaffBooking.ServiceReference.ViewAllRequestsResponseBody Body;
        
        public ViewAllRequestsResponse() {
        }
        
        public ViewAllRequestsResponse(StaffBooking.ServiceReference.ViewAllRequestsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class ViewAllRequestsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StaffBooking.ServiceReference.ArrayOfString[] ViewAllRequestsResult;
        
        public ViewAllRequestsResponseBody() {
        }
        
        public ViewAllRequestsResponseBody(StaffBooking.ServiceReference.ArrayOfString[] ViewAllRequestsResult) {
            this.ViewAllRequestsResult = ViewAllRequestsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : StaffBooking.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<StaffBooking.ServiceReference.WebServiceSoap>, StaffBooking.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffBooking.ServiceReference.LoginStaffResponse StaffBooking.ServiceReference.WebServiceSoap.LoginStaff(StaffBooking.ServiceReference.LoginStaffRequest request) {
            return base.Channel.LoginStaff(request);
        }
        
        public bool LoginStaff(string staffId, string password) {
            StaffBooking.ServiceReference.LoginStaffRequest inValue = new StaffBooking.ServiceReference.LoginStaffRequest();
            inValue.Body = new StaffBooking.ServiceReference.LoginStaffRequestBody();
            inValue.Body.staffId = staffId;
            inValue.Body.password = password;
            StaffBooking.ServiceReference.LoginStaffResponse retVal = ((StaffBooking.ServiceReference.WebServiceSoap)(this)).LoginStaff(inValue);
            return retVal.Body.LoginStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffBooking.ServiceReference.LoginStaffResponse> StaffBooking.ServiceReference.WebServiceSoap.LoginStaffAsync(StaffBooking.ServiceReference.LoginStaffRequest request) {
            return base.Channel.LoginStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffBooking.ServiceReference.LoginStaffResponse> LoginStaffAsync(string staffId, string password) {
            StaffBooking.ServiceReference.LoginStaffRequest inValue = new StaffBooking.ServiceReference.LoginStaffRequest();
            inValue.Body = new StaffBooking.ServiceReference.LoginStaffRequestBody();
            inValue.Body.staffId = staffId;
            inValue.Body.password = password;
            return ((StaffBooking.ServiceReference.WebServiceSoap)(this)).LoginStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffBooking.ServiceReference.UserDetailsResponse StaffBooking.ServiceReference.WebServiceSoap.UserDetails(StaffBooking.ServiceReference.UserDetailsRequest request) {
            return base.Channel.UserDetails(request);
        }
        
        public StaffBooking.ServiceReference.ArrayOfString UserDetails(string staffID) {
            StaffBooking.ServiceReference.UserDetailsRequest inValue = new StaffBooking.ServiceReference.UserDetailsRequest();
            inValue.Body = new StaffBooking.ServiceReference.UserDetailsRequestBody();
            inValue.Body.staffID = staffID;
            StaffBooking.ServiceReference.UserDetailsResponse retVal = ((StaffBooking.ServiceReference.WebServiceSoap)(this)).UserDetails(inValue);
            return retVal.Body.UserDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffBooking.ServiceReference.UserDetailsResponse> StaffBooking.ServiceReference.WebServiceSoap.UserDetailsAsync(StaffBooking.ServiceReference.UserDetailsRequest request) {
            return base.Channel.UserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffBooking.ServiceReference.UserDetailsResponse> UserDetailsAsync(string staffID) {
            StaffBooking.ServiceReference.UserDetailsRequest inValue = new StaffBooking.ServiceReference.UserDetailsRequest();
            inValue.Body = new StaffBooking.ServiceReference.UserDetailsRequestBody();
            inValue.Body.staffID = staffID;
            return ((StaffBooking.ServiceReference.WebServiceSoap)(this)).UserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffBooking.ServiceReference.MakeRequestResponse StaffBooking.ServiceReference.WebServiceSoap.MakeRequest(StaffBooking.ServiceReference.MakeRequestRequest request) {
            return base.Channel.MakeRequest(request);
        }
        
        public void MakeRequest(string staffID, System.DateTime start, System.DateTime end) {
            StaffBooking.ServiceReference.MakeRequestRequest inValue = new StaffBooking.ServiceReference.MakeRequestRequest();
            inValue.Body = new StaffBooking.ServiceReference.MakeRequestRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.start = start;
            inValue.Body.end = end;
            StaffBooking.ServiceReference.MakeRequestResponse retVal = ((StaffBooking.ServiceReference.WebServiceSoap)(this)).MakeRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffBooking.ServiceReference.MakeRequestResponse> StaffBooking.ServiceReference.WebServiceSoap.MakeRequestAsync(StaffBooking.ServiceReference.MakeRequestRequest request) {
            return base.Channel.MakeRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffBooking.ServiceReference.MakeRequestResponse> MakeRequestAsync(string staffID, System.DateTime start, System.DateTime end) {
            StaffBooking.ServiceReference.MakeRequestRequest inValue = new StaffBooking.ServiceReference.MakeRequestRequest();
            inValue.Body = new StaffBooking.ServiceReference.MakeRequestRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.start = start;
            inValue.Body.end = end;
            return ((StaffBooking.ServiceReference.WebServiceSoap)(this)).MakeRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffBooking.ServiceReference.ViewAllRequestsResponse StaffBooking.ServiceReference.WebServiceSoap.ViewAllRequests(StaffBooking.ServiceReference.ViewAllRequestsRequest request) {
            return base.Channel.ViewAllRequests(request);
        }
        
        public StaffBooking.ServiceReference.ArrayOfString[] ViewAllRequests(string staffID) {
            StaffBooking.ServiceReference.ViewAllRequestsRequest inValue = new StaffBooking.ServiceReference.ViewAllRequestsRequest();
            inValue.Body = new StaffBooking.ServiceReference.ViewAllRequestsRequestBody();
            inValue.Body.staffID = staffID;
            StaffBooking.ServiceReference.ViewAllRequestsResponse retVal = ((StaffBooking.ServiceReference.WebServiceSoap)(this)).ViewAllRequests(inValue);
            return retVal.Body.ViewAllRequestsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffBooking.ServiceReference.ViewAllRequestsResponse> StaffBooking.ServiceReference.WebServiceSoap.ViewAllRequestsAsync(StaffBooking.ServiceReference.ViewAllRequestsRequest request) {
            return base.Channel.ViewAllRequestsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffBooking.ServiceReference.ViewAllRequestsResponse> ViewAllRequestsAsync(string staffID) {
            StaffBooking.ServiceReference.ViewAllRequestsRequest inValue = new StaffBooking.ServiceReference.ViewAllRequestsRequest();
            inValue.Body = new StaffBooking.ServiceReference.ViewAllRequestsRequestBody();
            inValue.Body.staffID = staffID;
            return ((StaffBooking.ServiceReference.WebServiceSoap)(this)).ViewAllRequestsAsync(inValue);
        }
    }
}
