//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApp.SOAPServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://localhost:63341/WebService.asmx", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:63341/WebService.asmx", ConfigurationName="SOAPServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name staffId from namespace http://localhost:63341/WebService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/LoginStaff", ReplyAction="*")]
        MobileApp.SOAPServiceReference.LoginStaffResponse LoginStaff(MobileApp.SOAPServiceReference.LoginStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/LoginStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.LoginStaffResponse> LoginStaffAsync(MobileApp.SOAPServiceReference.LoginStaffRequest request);
        
        // CODEGEN: Generating message contract since element name staffID from namespace http://localhost:63341/WebService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/UserDetails", ReplyAction="*")]
        MobileApp.SOAPServiceReference.UserDetailsResponse UserDetails(MobileApp.SOAPServiceReference.UserDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/UserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.UserDetailsResponse> UserDetailsAsync(MobileApp.SOAPServiceReference.UserDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name staffID from namespace http://localhost:63341/WebService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/MakeRequest", ReplyAction="*")]
        MobileApp.SOAPServiceReference.MakeRequestResponse MakeRequest(MobileApp.SOAPServiceReference.MakeRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/MakeRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.MakeRequestResponse> MakeRequestAsync(MobileApp.SOAPServiceReference.MakeRequestRequest request);
        
        // CODEGEN: Generating message contract since element name staffID from namespace http://localhost:63341/WebService.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/ViewAllRequests", ReplyAction="*")]
        MobileApp.SOAPServiceReference.ViewAllRequestsResponse ViewAllRequests(MobileApp.SOAPServiceReference.ViewAllRequestsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:63341/WebService.asmx/ViewAllRequests", ReplyAction="*")]
        System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.ViewAllRequestsResponse> ViewAllRequestsAsync(MobileApp.SOAPServiceReference.ViewAllRequestsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginStaff", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public MobileApp.SOAPServiceReference.LoginStaffRequestBody Body;
        
        public LoginStaffRequest() {
        }
        
        public LoginStaffRequest(MobileApp.SOAPServiceReference.LoginStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class LoginStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginStaffRequestBody() {
        }
        
        public LoginStaffRequestBody(string staffId, string password) {
            this.staffId = staffId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginStaffResponse", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public MobileApp.SOAPServiceReference.LoginStaffResponseBody Body;
        
        public LoginStaffResponse() {
        }
        
        public LoginStaffResponse(MobileApp.SOAPServiceReference.LoginStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class LoginStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginStaffResult;
        
        public LoginStaffResponseBody() {
        }
        
        public LoginStaffResponseBody(bool LoginStaffResult) {
            this.LoginStaffResult = LoginStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserDetails", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public MobileApp.SOAPServiceReference.UserDetailsRequestBody Body;
        
        public UserDetailsRequest() {
        }
        
        public UserDetailsRequest(MobileApp.SOAPServiceReference.UserDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class UserDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffID;
        
        public UserDetailsRequestBody() {
        }
        
        public UserDetailsRequestBody(string staffID) {
            this.staffID = staffID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserDetailsResponse", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public MobileApp.SOAPServiceReference.UserDetailsResponseBody Body;
        
        public UserDetailsResponse() {
        }
        
        public UserDetailsResponse(MobileApp.SOAPServiceReference.UserDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class UserDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MobileApp.SOAPServiceReference.ArrayOfString UserDetailsResult;
        
        public UserDetailsResponseBody() {
        }
        
        public UserDetailsResponseBody(MobileApp.SOAPServiceReference.ArrayOfString UserDetailsResult) {
            this.UserDetailsResult = UserDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeRequest", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public MobileApp.SOAPServiceReference.MakeRequestRequestBody Body;
        
        public MakeRequestRequest() {
        }
        
        public MakeRequestRequest(MobileApp.SOAPServiceReference.MakeRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class MakeRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime start;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime end;
        
        public MakeRequestRequestBody() {
        }
        
        public MakeRequestRequestBody(string staffID, System.DateTime start, System.DateTime end) {
            this.staffID = staffID;
            this.start = start;
            this.end = end;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeRequestResponse", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public MobileApp.SOAPServiceReference.MakeRequestResponseBody Body;
        
        public MakeRequestResponse() {
        }
        
        public MakeRequestResponse(MobileApp.SOAPServiceReference.MakeRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MakeRequestResponseBody {
        
        public MakeRequestResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewAllRequestsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewAllRequests", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public MobileApp.SOAPServiceReference.ViewAllRequestsRequestBody Body;
        
        public ViewAllRequestsRequest() {
        }
        
        public ViewAllRequestsRequest(MobileApp.SOAPServiceReference.ViewAllRequestsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class ViewAllRequestsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffID;
        
        public ViewAllRequestsRequestBody() {
        }
        
        public ViewAllRequestsRequestBody(string staffID) {
            this.staffID = staffID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewAllRequestsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewAllRequestsResponse", Namespace="http://localhost:63341/WebService.asmx", Order=0)]
        public MobileApp.SOAPServiceReference.ViewAllRequestsResponseBody Body;
        
        public ViewAllRequestsResponse() {
        }
        
        public ViewAllRequestsResponse(MobileApp.SOAPServiceReference.ViewAllRequestsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:63341/WebService.asmx")]
    public partial class ViewAllRequestsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MobileApp.SOAPServiceReference.ArrayOfString[] ViewAllRequestsResult;
        
        public ViewAllRequestsResponseBody() {
        }
        
        public ViewAllRequestsResponseBody(MobileApp.SOAPServiceReference.ArrayOfString[] ViewAllRequestsResult) {
            this.ViewAllRequestsResult = ViewAllRequestsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : MobileApp.SOAPServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<MobileApp.SOAPServiceReference.WebServiceSoap>, MobileApp.SOAPServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileApp.SOAPServiceReference.LoginStaffResponse MobileApp.SOAPServiceReference.WebServiceSoap.LoginStaff(MobileApp.SOAPServiceReference.LoginStaffRequest request) {
            return base.Channel.LoginStaff(request);
        }
        
        public bool LoginStaff(string staffId, string password) {
            MobileApp.SOAPServiceReference.LoginStaffRequest inValue = new MobileApp.SOAPServiceReference.LoginStaffRequest();
            inValue.Body = new MobileApp.SOAPServiceReference.LoginStaffRequestBody();
            inValue.Body.staffId = staffId;
            inValue.Body.password = password;
            MobileApp.SOAPServiceReference.LoginStaffResponse retVal = ((MobileApp.SOAPServiceReference.WebServiceSoap)(this)).LoginStaff(inValue);
            return retVal.Body.LoginStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.LoginStaffResponse> MobileApp.SOAPServiceReference.WebServiceSoap.LoginStaffAsync(MobileApp.SOAPServiceReference.LoginStaffRequest request) {
            return base.Channel.LoginStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.LoginStaffResponse> LoginStaffAsync(string staffId, string password) {
            MobileApp.SOAPServiceReference.LoginStaffRequest inValue = new MobileApp.SOAPServiceReference.LoginStaffRequest();
            inValue.Body = new MobileApp.SOAPServiceReference.LoginStaffRequestBody();
            inValue.Body.staffId = staffId;
            inValue.Body.password = password;
            return ((MobileApp.SOAPServiceReference.WebServiceSoap)(this)).LoginStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileApp.SOAPServiceReference.UserDetailsResponse MobileApp.SOAPServiceReference.WebServiceSoap.UserDetails(MobileApp.SOAPServiceReference.UserDetailsRequest request) {
            return base.Channel.UserDetails(request);
        }
        
        public MobileApp.SOAPServiceReference.ArrayOfString UserDetails(string staffID) {
            MobileApp.SOAPServiceReference.UserDetailsRequest inValue = new MobileApp.SOAPServiceReference.UserDetailsRequest();
            inValue.Body = new MobileApp.SOAPServiceReference.UserDetailsRequestBody();
            inValue.Body.staffID = staffID;
            MobileApp.SOAPServiceReference.UserDetailsResponse retVal = ((MobileApp.SOAPServiceReference.WebServiceSoap)(this)).UserDetails(inValue);
            return retVal.Body.UserDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.UserDetailsResponse> MobileApp.SOAPServiceReference.WebServiceSoap.UserDetailsAsync(MobileApp.SOAPServiceReference.UserDetailsRequest request) {
            return base.Channel.UserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.UserDetailsResponse> UserDetailsAsync(string staffID) {
            MobileApp.SOAPServiceReference.UserDetailsRequest inValue = new MobileApp.SOAPServiceReference.UserDetailsRequest();
            inValue.Body = new MobileApp.SOAPServiceReference.UserDetailsRequestBody();
            inValue.Body.staffID = staffID;
            return ((MobileApp.SOAPServiceReference.WebServiceSoap)(this)).UserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileApp.SOAPServiceReference.MakeRequestResponse MobileApp.SOAPServiceReference.WebServiceSoap.MakeRequest(MobileApp.SOAPServiceReference.MakeRequestRequest request) {
            return base.Channel.MakeRequest(request);
        }
        
        public void MakeRequest(string staffID, System.DateTime start, System.DateTime end) {
            MobileApp.SOAPServiceReference.MakeRequestRequest inValue = new MobileApp.SOAPServiceReference.MakeRequestRequest();
            inValue.Body = new MobileApp.SOAPServiceReference.MakeRequestRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.start = start;
            inValue.Body.end = end;
            MobileApp.SOAPServiceReference.MakeRequestResponse retVal = ((MobileApp.SOAPServiceReference.WebServiceSoap)(this)).MakeRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.MakeRequestResponse> MobileApp.SOAPServiceReference.WebServiceSoap.MakeRequestAsync(MobileApp.SOAPServiceReference.MakeRequestRequest request) {
            return base.Channel.MakeRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.MakeRequestResponse> MakeRequestAsync(string staffID, System.DateTime start, System.DateTime end) {
            MobileApp.SOAPServiceReference.MakeRequestRequest inValue = new MobileApp.SOAPServiceReference.MakeRequestRequest();
            inValue.Body = new MobileApp.SOAPServiceReference.MakeRequestRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.start = start;
            inValue.Body.end = end;
            return ((MobileApp.SOAPServiceReference.WebServiceSoap)(this)).MakeRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobileApp.SOAPServiceReference.ViewAllRequestsResponse MobileApp.SOAPServiceReference.WebServiceSoap.ViewAllRequests(MobileApp.SOAPServiceReference.ViewAllRequestsRequest request) {
            return base.Channel.ViewAllRequests(request);
        }
        
        public MobileApp.SOAPServiceReference.ArrayOfString[] ViewAllRequests(string staffID) {
            MobileApp.SOAPServiceReference.ViewAllRequestsRequest inValue = new MobileApp.SOAPServiceReference.ViewAllRequestsRequest();
            inValue.Body = new MobileApp.SOAPServiceReference.ViewAllRequestsRequestBody();
            inValue.Body.staffID = staffID;
            MobileApp.SOAPServiceReference.ViewAllRequestsResponse retVal = ((MobileApp.SOAPServiceReference.WebServiceSoap)(this)).ViewAllRequests(inValue);
            return retVal.Body.ViewAllRequestsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.ViewAllRequestsResponse> MobileApp.SOAPServiceReference.WebServiceSoap.ViewAllRequestsAsync(MobileApp.SOAPServiceReference.ViewAllRequestsRequest request) {
            return base.Channel.ViewAllRequestsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MobileApp.SOAPServiceReference.ViewAllRequestsResponse> ViewAllRequestsAsync(string staffID) {
            MobileApp.SOAPServiceReference.ViewAllRequestsRequest inValue = new MobileApp.SOAPServiceReference.ViewAllRequestsRequest();
            inValue.Body = new MobileApp.SOAPServiceReference.ViewAllRequestsRequestBody();
            inValue.Body.staffID = staffID;
            return ((MobileApp.SOAPServiceReference.WebServiceSoap)(this)).ViewAllRequestsAsync(inValue);
        }
    }
}
